### ISSUE TITLE
Figure out why growing preview on annonate does not work

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#155]

**Comment by KillerX** [comment]
I have tested several options that should have solved the issue but it appears that there is some kind of manipulation of the video going on by Vidispine/Cantemo that completely breaks any attempts I made. The player used is also not a very modern one and does not seem to support many of the moden tools.

Conclusion:

* The issue is not because of the new process, it existed before. New recordings may or may not work while still growing
* Nothing we can do now short of writing our own tool
* Cantemo 6 is around the corner with upgraded players. Testing to begin soonest
* We will have to live with the state as of now
