### ISSUE TITLE
Make sure upload form works for bmm

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-flows#284]
upload form, select integration , shows up in the integration environment

select language and end up at correct place

**Comment by KillerX** [comment]
The form is now fixed to the point that I was able to upload a file, have it appear in MB, and be exported.
As of this moment BMM complains about the language code being unexpected. I suspect this is because the language code we get from BMM is being passed straight through. I will try to convert it and see if that helps.

**Comment by KillerX** [comment]
Known bug: Multiple uploads cause progress bar to flicker.

**Comment by KillerX** [comment]
@kkuepper feel free to test, the latest version is deployed on tools.bcc.media

2 Known issues:

* Multiple uploads cause the progress bar to flicker. It's a "bad" implementation in VUE that is meant to only support one upload total.
* if the url does not end in a `/` then refresh lands you on a 404

**Comment by kkuepper** [comment]
test results:
- When opening the form, I see "You don't have enough permissions" for 1 second. I guess that's because that's the default message. Would be better to show a loading spinner, or nothing at all, while it's verifying  my permission
- after selecting norwegian and going to the upload form, the language dropdown is not prefilled with norwegian
- How can I access the admin area and try out different permissions?
- I guess I only have permission for norwegian, but I still see the language dropdown with only norwegian as available option. If I only have 1 choice don't make me click
- setting a title doesn't actually change the title in BMM


Nice touch with the "Upload more button"

**Comment by KillerX** [comment]
> after selecting norwegian and going to the upload form, the language dropdown is not prefilled with norwegian

Fixed, old config value that had "no" instead of "nb". Updated for all users

> How can I access the admin area and try out different permissions?
https://tools.bcc.media/admin/ (not the final /, ref known bug in my previous comment)

> setting a title doesn't actually change the title in BMM
Am I missing something in the data there or is this an update you have to do?

**Comment by kkuepper** [comment]
> > setting a title doesn't actually change the title in BMM
> 
> Am I missing something in the data there or is this an update you have to do?

I think right now, BMM sets the title only if it's empty. Not sure if I should change that or not.

**Comment by KillerX** [comment]
> > > setting a title doesn't actually change the title in BMM
> > 
> > 
> > Am I missing something in the data there or is this an update you have to do?
> 
> I think right now, BMM sets the title only if it's empty. Not sure if I should change that or not. But the form requires me to set a title. It shouldn't require me to set a title, if there's already a title. We can talk it through on Monday.

Maybe I can update the text to say "The title will only be update in BMM if there is no title already present"? And then we can see if there is an outcry about that.

**Comment by KillerX** [comment]
> > > > setting a title doesn't actually change the title in BMM
> > > 
> > > 
> > > Am I missing something in the data there or is this an update you have to do?
> > 
> > 
> > I think right now, BMM sets the title only if it's empty. Not sure if I should change that or not. But the form requires me to set a title. It shouldn't require me to set a title, if there's already a title. We can talk it through on Monday.
> 
> Maybe I can update the text to say "The title will only be update in BMM if there is no title already present"? And then we can see if there is an outcry about that.

Done

> When opening the form, I see "You don't have enough permissions" for 1 second. I guess that's because that's the default message. Would be better to show a loading spinner, or nothing at all, while it's verifying my permission

Done

I believe this should address all the comments.

**Comment by KillerX** [comment]
* Add trailing slash to link
* Podcasts not auto loading ???
* Optional title
